"""Interactive Git Versioneer - Gestor interactivo de versiones Git."""

import sys
from pathlib import Path

__app_name__ = "igv"
__package_name__ = "interactive-git-versioneer"

try:
    from importlib.metadata import PackageNotFoundError, version
except ImportError:
    # Python < 3.8
    from importlib_metadata import PackageNotFoundError, version


def _get_version() -> str:
    """Retrieves the package version.

    It attempts to get the version from `_version.py` (generated by setuptools_scm),
    then from `importlib.metadata` (for installed packages).

    Returns:
        str: The determined version string of the package.
    """
    # Estrategia 1: Leer desde _version.py (generado por setuptools_scm)
    try:
        from interactive_git_versioneer._version import version as scm_version
        return scm_version
    except ImportError:
        pass

    # Estrategia 2: importlib.metadata (funciona para paquetes instalados)
    try:
        return version(__package_name__)
    except PackageNotFoundError:
        pass

    # Fallback: Si setuptools_scm no generó _version.py y el paquete no está instalado,
    # significa que estamos en un entorno donde setuptools_scm no ha ejecutado o
    # no hay tags. Para este caso, podemos tener un valor predeterminado o levantar un error.
    # Por simplicidad, y dado que setuptools_scm siempre debería proveer un valor en un repo git,
    # podemos levantar un error si no se espera este caso
    return "unknown"


__version__ = _get_version()

__all__ = ["__app_name__", "__package_name__", "__version__"]
